# Generated by Django 3.0.5 on 2020-04-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paynow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayAnotherUserWallet',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('paynow.wallet',),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='txn_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Credit'), (1, 'Withdraw'), (2, 'Send'), (3, 'Request')]),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='wallet_address',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
